import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowLeft,Download,Eye,Mail,MapPin,Phone,Pencil,Upload,UserCheck,CheckCircle2,ShieldCheck,GraduationCap,BriefcaseBusiness,FileCheck2,BrainCircuit} from 'lucide-react';
import {api} from '../services/api';
import {useAuth} from '../context/AuthContext';
import {Badge,Loader} from '../components/UI';

const tabs=['Overview','Candidate Profile','Employment','Education','Identity','Offer History','Documents','Activity'];
const titleCase=v=>(v||'').replace(/\b\w/g,ch=>ch.toUpperCase());
const labelCase=v=>v.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase());

export default function CandidateDetails(){
 const {user}=useAuth();
 const {id}=useParams();const [c,setC]=useState(null);const [error,setError]=useState('');const [tab,setTab]=useState('Overview');const [file,setFile]=useState(null);const [type,setType]=useState('RESUME');const [hiring,setHiring]=useState(false);
 const load=()=>{setError('');return api.candidate(id).then(setC).catch(e=>{setError(e.message||'Unable To Load Candidate Details.');setC(null)})};
 useEffect(()=>{load()},[id]);
 if(error)return <article className="panel error-panel"><h3>Candidate Details Could Not Be Loaded</h3><p>{error}</p><button className="btn" onClick={load}>Try Again</button></article>;
 if(!c)return <Loader/>;
 const canModify=user?.role==='ADMIN'||Number(c.createdByUserId)===Number(user?.id);
 const upload=async()=>{if(!file)return;await api.upload(id,type,file);setFile(null);load()};
 const hire=async()=>{if(!confirm(`Hire ${c.name} For ${c.position}?`))return;setHiring(true);try{await api.hire(id);await load()}catch(e){alert(e.message||'Unable To Hire Candidate.')}finally{setHiring(false)}};
 const download=async()=>{try{const blob=await api.report(id);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`CrossCheck-${c.name?.replace(/\s+/g,'-')||'Candidate'}-Report.pdf`;a.click();URL.revokeObjectURL(url)}catch(e){alert(e.message||'Unable To Download Report.')}};
 return <>
  <div className="candidate-back-row"><Link to="/app/candidates"><ArrowLeft size={16}/> Back To Candidates</Link><div className="page-actions"><button className="btn secondary" onClick={download}><Download size={16}/> Download Report</button>{canModify&&<Link className="btn secondary" to={`/app/candidates/${id}/edit`}><Pencil size={16}/> Edit Candidate</Link>}{c.hiringStatus==='HIRED'?<span className="btn hired-button"><UserCheck size={16}/> Hired</span>:<button className="btn hire-button" onClick={hire} disabled={hiring}><UserCheck size={16}/>{hiring?'Hiring…':'Hire Candidate'}</button>}</div></div>
  <section className="review-profile-card"><div className="review-profile-main"><div className="candidate-detail-photo large">{c.photoData?<img src={c.photoData} alt={`${c.name} Profile`}/>:<span>{c.name?.[0]?.toUpperCase()}</span>}</div><div><div className="name-risk-row"><h1>{titleCase(c.name)}</h1><Badge value={`${c.riskLevel} RISK`}/></div><h3>{titleCase(c.position)}</h3><div className="contact-lines"><span><Phone size={15}/>{c.mobileNumber||'Not Provided'}</span><span><Mail size={15}/>{c.email}</span><span><MapPin size={15}/>{titleCase(c.currentCompany)||'Location Not Provided'}</span></div></div></div><div className="review-summary"><div><small>Hiring Trust Score</small><b>{100-c.riskScore}/100</b></div><div><small>Joining Probability</small><b>{c.joiningProbability}%</b></div><div><small>Verification Status</small><Badge value={c.verificationStatus}/></div></div></section>
  <div className="tabs profile-tabs">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
  <article className="panel details-panel">
   {tab==='Overview'&&<Overview c={c}/>} 
   {tab==='Candidate Profile'&&<Info c={c}/>} 
   {tab==='Employment'&&<VerificationSection title="Employment Verification" icon={<BriefcaseBusiness/>}><Info c={{currentCompany:c.currentCompany,previousCompany:c.previousCompany,joiningDate:c.joiningDate,relievingDate:c.relievingDate,employmentGapMonths:c.employmentGapMonths,employmentStatus:c.employmentStatus}}/><Verify id={id} c={c} load={load} target="employment"/></VerificationSection>}
   {tab==='Education'&&<VerificationSection title="Education Verification" icon={<GraduationCap/>}><Info c={{degree:c.degree,university:c.university,graduationYear:c.graduationYear,marks:c.marks,educationStatus:c.educationStatus}}/><Verify id={id} c={c} load={load} target="education"/></VerificationSection>}
   {tab==='Identity'&&<Identity c={c} id={id} load={load}/>} 
   {tab==='Offer History'&&<OfferVerification c={c} id={id} load={load}/>}
   {tab==='Documents'&&<div><h3>Document Verification</h3><div className="upload-row"><select value={type} onChange={e=>setType(e.target.value)}>{['RESUME','AADHAAR','PAN','PASSPORT','EXPERIENCE_LETTER','SALARY_SLIP','OFFER_LETTER'].map(x=><option key={x}>{x.replaceAll('_',' ')}</option>)}</select><input type="file" onChange={e=>setFile(e.target.files[0])}/><button className="btn" onClick={upload}><Upload size={16}/> Upload Document</button></div><div className="doc-grid">{(c.documents||[]).map(d=><div key={d.id||`${d.type}-${d.fileName}`}><b>{d.type?.replaceAll('_',' ')}</b><small>{d.fileName}</small><Badge value={d.status}/></div>)}</div></div>}
   {tab==='Activity'&&<div><h3>Candidate Activity</h3>{(c.activities||[]).map((a,i)=><div key={`${a.action}-${i}`} className="activity"><span></span><div><b>{titleCase(a.action)}</b><small>{a.createdAt}</small></div></div>)}</div>}
  </article>
 </>;
}

function Overview({c}){const trust=100-c.riskScore;const checks=[['Multiple Offers Check',c.activeOffers>0?`${c.activeOffers} Active Offer(s)`:'No Active Offers Found',c.activeOffers>0?'PENDING':'VERIFIED',<BrainCircuit/>],['Employment Verification',c.employmentStatus==='VERIFIED'?'Employment Details Verified':'Employment Review Required',c.employmentStatus,<BriefcaseBusiness/>],['Education Verification',c.educationStatus==='VERIFIED'?'Education Details Verified':'Education Review Required',c.educationStatus,<GraduationCap/>],['Identity Verification',c.identityStatus==='VERIFIED'?'Aadhaar, PAN Or Passport Verified':'Identity Review Required',c.identityStatus,<ShieldCheck/>],['Offer Letter Verification',c.offerLetterData?(c.offerLetterStatus==='VERIFIED'?'Offer Letter Reviewed And Verified':'Offer Letter Review Required'):'Offer Letter Not Uploaded',c.offerLetterStatus||'PENDING',<FileCheck2/>],['Document Verification',(c.documents||[]).length?`${(c.documents||[]).filter(d=>d.status==='VERIFIED').length} Of ${(c.documents||[]).length} Verified`:'No Documents Uploaded',c.verificationStatus,<FileCheck2/>]];return <div className="review-overview-grid"><section className="trust-card"><h3>Hiring Trust Score</h3><div className="score-ring" style={{'--score':trust}}><div><b>{trust}</b><span>/100</span></div></div><Badge value={`${c.riskLevel} RISK`}/><p>{c.aiReason||'Candidate Risk And Verification Summary.'}</p></section><section className="joining-card"><h3>Joining Probability</h3><div className="joining-number">{c.joiningProbability}%</div><div className="progress-track"><span style={{width:`${c.joiningProbability}%`}}></span></div><h4>Key Factors</h4><ul className="key-factors"><li><CheckCircle2/>Notice Period: {c.noticePeriodDays} Days</li><li><CheckCircle2/>{c.activeOffers>0?'Competing Offers Detected':'No Active Competing Offers'}</li><li><CheckCircle2/>{c.employmentGapMonths>3?'Employment Gap Needs Review':'Stable Employment History'}</li><li><CheckCircle2/>Candidate Interest: {c.candidateInterest||0}%</li></ul></section><section className="crosscheck-report"><div className="report-title"><div><h2>CrossCheck Report</h2><p>Complete Candidate Verification Summary</p></div><Download size={22}/></div>{checks.map(([title,sub,status,icon])=><div className="report-check" key={title}><span className="report-icon">{icon}</span><div><b>{title}</b><small>{sub}</small></div><Badge value={status||'PENDING'}/></div>)}<div className="ai-recommendation"><BrainCircuit/><div><b>AI Recommendation</b><p>{c.aiRecommendation}. {c.aiReason}</p></div></div></section></div>}
function VerificationSection({title,icon,children}){return <div className="verification-section"><div className="verification-heading">{icon}<h3>{title}</h3></div>{children}</div>}
function Info({c}){const hidden=['photoData','photoFileName','aadhaarDocumentData','panDocumentData','passportDocumentData','offerLetterData'];return <div className="info-grid">{Object.entries(c).filter(([k,v])=>!hidden.includes(k)&&v!==null&&v!==undefined&&v!==''&&typeof v!=='object').map(([k,v])=><div key={k}><small>{labelCase(k)}</small><b>{typeof v==='string'?(v.includes('@')?v:titleCase(v)):String(v)}</b></div>)}</div>}
function mask(v,type){if(!v)return 'Not Provided';if(type==='aadhaar')return `XXXX XXXX ${v.slice(-4)}`;if(type==='pan')return `${v.slice(0,3)}****${v.slice(-3)}`;return `${v.slice(0,2)}*****${v.slice(-2)}`}
function Identity({c,id,load}){const open=data=>{if(data)window.open(data,'_blank','noopener,noreferrer')};return <div><div className="identity-review-head"><div><h3>Identity Verification</h3><p>Review Identity Numbers And Uploaded Proof Before Changing The Status.</p></div><Badge value={c.identityStatus||'PENDING'}/></div><div className="identity-review-grid"><IdentityCard title="Aadhaar Card" number={mask(c.aadhaarNumber,'aadhaar')} name={c.aadhaarDocumentName} data={c.aadhaarDocumentData} open={open}/><IdentityCard title="PAN Card" number={mask(c.panNumber,'pan')} name={c.panDocumentName} data={c.panDocumentData} open={open}/><IdentityCard title="Passport" number={mask(c.passportNumber,'passport')} name={c.passportDocumentName} data={c.passportDocumentData} open={open}/></div><Verify id={id} c={c} load={load} target="identity"/></div>}
function IdentityCard({title,number,name,data,open}){return <article className="identity-review-card"><h4>{title}</h4><small>Document Number</small><b>{number}</b><small>Uploaded Proof</small><span>{name||'Not Uploaded'}</span>{data&&<button className="btn secondary" onClick={()=>open(data)}><Eye size={16}/> View Document</button>}</article>}
function Verify({id,c,load,target}){const run=async status=>{const body={employmentStatus:c.employmentStatus,educationStatus:c.educationStatus,identityStatus:c.identityStatus,verificationStatus:c.verificationStatus};body[`${target}Status`]=status;const values=[body.employmentStatus,body.educationStatus,body.identityStatus];body.verificationStatus=values.every(v=>v==='VERIFIED')?'VERIFIED':values.some(v=>v==='FAILED')?'FAILED':'PENDING';await api.verify(id,body);load()};const name=titleCase(target);return <div className="verify-actions"><button className="btn" onClick={()=>run('VERIFIED')}>Mark {name} Verified</button><button className="btn secondary" onClick={()=>run('PENDING')}>Mark Pending</button><button className="btn danger" onClick={()=>run('FAILED')}>Mark Failed</button></div>}

function OfferVerification({c,id,load}){const [remarks,setRemarks]=useState(c.offerVerificationRemarks||'');const open=()=>c.offerLetterData&&window.open(c.offerLetterData,'_blank','noopener,noreferrer');const run=async status=>{try{await api.verifyOffer(id,{status,remarks});await load()}catch(e){alert(e.message||'Unable To Update Offer Letter Verification.')}};const comparison=[['Candidate Name',c.name,c.offerCandidateName],['Position',c.position,c.offerPosition],['Company Name',c.currentCompany,c.offerCompanyName]];return <div className="offer-review"><div className="identity-review-head"><div><h3>Offer Letter Verification</h3><p>Compare The Uploaded Offer Letter With The Candidate Profile And Record The Manual Review Result.</p></div><Badge value={c.offerLetterStatus||'PENDING'}/></div><div className="offer-review-grid"><article className="identity-review-card"><h4>Uploaded Offer Letter</h4><small>File Name</small><b>{c.offerLetterName||'Not Uploaded'}</b><small>Offer Reference</small><span>{c.offerReferenceNumber||'Not Provided'}</span>{c.offerLetterData&&<button className="btn secondary" onClick={open}><Eye size={16}/> View Offer Letter</button>}</article><article className="identity-review-card"><h4>Offer Details</h4><small>Offer Date</small><b>{c.offerDate||'Not Provided'}</b><small>Proposed Joining Date</small><span>{c.proposedJoiningDate||'Not Provided'}</span><small>Offered Salary</small><span>{c.offerSalary||'Not Provided'}</span></article><article className="identity-review-card"><h4>Verification Record</h4><small>Verified By</small><b>{c.offerVerifiedBy||'Not Reviewed'}</b><small>Verified At</small><span>{c.offerVerifiedAt?new Date(c.offerVerifiedAt).toLocaleString():'Not Reviewed'}</span></article></div><div className="offer-compare"><h4>Profile Comparison</h4>{comparison.map(([label,profile,offer])=>{const mismatch=profile&&offer&&String(profile).toLowerCase()!==String(offer).toLowerCase();return <div key={label} className={mismatch?'mismatch':''}><b>{label}</b><span>Profile: {profile||'Not Provided'}</span><span>Offer: {offer||'Not Provided'}</span><Badge value={mismatch?'MISMATCH':'MATCH'}/></div>})}</div><label>Verification Remarks<textarea value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder="Add Review Notes, Employer Confirmation Or Mismatch Details"/></label><div className="verify-actions"><button className="btn" onClick={()=>run('VERIFIED')}>Mark Offer Verified</button><button className="btn secondary" onClick={()=>run('PENDING')}>Mark Pending</button><button className="btn danger" onClick={()=>run('MISMATCH')}>Mark Mismatch</button><button className="btn danger" onClick={()=>run('FAILED')}>Mark Failed</button></div><p className="verification-disclaimer">Verification Requires Human Review Or A Trusted Employer/Provider Confirmation. Uploading A File Alone Never Changes The Status To Verified.</p></div>}
